# Generated by Django 5.1.1 on 2025-03-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='packages/')),
                ('location', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('persons', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField(default=5.0)),
                ('description', models.TextField()),
            ],
        ),
    ]
