# Generated by Django 5.1.1 on 2025-03-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='inclusions',
            field=models.TextField(default='Includes basic amenities.'),
        ),
    ]
