# Generated by Django 5.1.1 on 2025-03-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_alter_order_package_booking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='tour_type',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Family', 'Family'), ('Honeymoon', 'Honeymoon'), ('Beach', 'Beach'), ('Cultural', 'Cultural'), ('Wildlife', 'Wildlife')], default='Adventure', max_length=50),
        ),
    ]
