# Generated by Django 5.1.1 on 2025-03-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_model',
            name='icon',
            field=models.CharField(help_text='FontAwesome v4 icons are supported. Example: fa fa-home', max_length=50),
        ),
    ]
