# Generated by Django 5.1.1 on 2025-03-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_model_icon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service_model',
            new_name='services',
        ),
    ]
