# Generated by Django 5.1.1 on 2025-03-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_service_model_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='service',
        ),
    ]
